
import java.util.Queue;

public class Queues {
  Queue<Integer> queue = new java.util.ArrayDeque<>();

  public static void reverse(Queue<Integer> queue) {
    Statck<Integer> stack = new Stack<>();

    if(!queue.isEmpty())
      stack.
  }


  public static void main(String[] args) {
    Queue<Integer> queue = new java.util.ArrayDeque<>();
    queue.add(10);
    queue.add(20);
    queue.add(30);
    System.out.println(queue);
  }
}